language: erlang
script: mix test
install: mix deps.get
otp_release:
  - R16B
before_install:
  - mkdir -p vendor/elixir
  - wget -q https://github.com/elixir-lang/elixir/releases/download/v0.10.2/v0.10.2.zip && unzip -qq v0.10.2.zip -d vendor/elixir
  - export PATH="$PATH:$PWD/vendor/elixir/bin"
  - export MIX_ENV=test
